dubbo:
  protocol:
    name: dubbo
    port: 20881
  provider:
    timeout: 5000
  registry:
    address: zookeeper://www.coolboy.fun:xxxx
  scan:
    base-packages: com.geekq.provider.service.impl
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.geekq.api.pojo
spring:
  transaction:
  application:
    name: miaosha-goods-provider
  datasource:
    url: jdbc:mysql://www.coolboy.fun:xxxx/miaosha?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: xxxx
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      # 监控配置
      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        reset-enable: false
      filter:
        log4j2:
          statement-executable-sql-log-enable: true  # 输出sql
        stat:
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 3000
        config:
          enabled: true
      # 连接池配置
      initial-size: 5
      max-active: 20
      max-wait: 60000 # 配置获取连接等待超时的时间
      min-idle: 5
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 'x'
      validation-query-timeout: 10000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j2,config # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  main:
    #不启动web
    web-application-type: none