version: '3.7'
services:
  miaosha-user:
    image: miaosha-user:latest
    restart: "no"
    network_mode: host
    hostname: localhost
    container_name: miaosha-user
    environment:
      - JAVA_OPTS=-server -Xms128m -Xmx128m -XX:+UseConcMarkSweepGC -XX:NewRatio=3 -XX:+UseContainerSupport -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=75 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/gc/miaosha-user.hprof -Xloggc:/var/log/gc/miaosha-user.log -verbose:gc
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - /share/software/miaosha/user:/data/jar
      - /share/software/miaosha/log:/var/log

  miaosha-goods:
    image: miaosha-goods:latest
    restart: "no"
    network_mode: host
    hostname: localhost
    container_name: miaosha-goods
    environment:
      - JAVA_OPTS=-server -Xms128m -Xmx128m -XX:+UseConcMarkSweepGC -XX:NewRatio=3 -XX:+UseContainerSupport -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=75 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/gc/miaosha-goods.hprof -Xloggc:/var/log/gc/miaosha-goods.log -verbose:gc
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - /share/software/miaosha/goods:/data/jar
      - /share/software/miaosha/log:/var/log

  miaosha-order:
    image: miaosha-order:latest
    restart: "no"
    network_mode: host
    hostname: localhost
    container_name: miaosha-order
    environment:
      - JAVA_OPTS=-server -Xms128m -Xmx128m -XX:+UseConcMarkSweepGC -XX:NewRatio=3 -XX:+UseContainerSupport -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=75 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/gc/miaosha-order.hprof -Xloggc:/var/log/gc/miaosha-order.log -verbose:gc
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - /share/software/miaosha/order:/data/jar
      - /share/software/miaosha/log:/var/log

  miaosha-web:
    image: miaosha-web:latest
    restart: "no"
    hostname: localhost
    network_mode: host
    container_name: miaosha-web
    environment:
      - JAVA_OPTS=-server -Xms256m -Xmx256m -XX:+UseConcMarkSweepGC -XX:NewRatio=3 -XX:+UseContainerSupport -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=75 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/gc/miaosha-web.hprof -Xloggc:/var/log/gc/miaosha-web.log -verbose:gc
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - /share/software/miaosha/web:/data/jar
      - /share/software/miaosha/log:/var/log

#networks:
#  default:
#    external:
#      name: "miaosha-net"
